# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "README.md"
      - "**.md"
      - "LICENSE**"
  workflow_dispatch:

jobs:
  stable_build:
    name: Stable Zig Compile and run Tests
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: setup-linux
        if: matrix.os == 'ubuntu-latest'
        run: | 
          sudo apt-get update && sudo apt-get install libsdl2-dev libsdl2-image-dev

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          # Find all folders containing build.zig, build.zig.zon, src/, src/main.zig
          projects=$(find . -type d ! -name "vkendeavors" -exec test -e "{}/build.zig" -a -e "{}/build.zig.zon" -a -e "{}/src/" -a -e "{}/src/main.zig" \; -print)
          
          echo $projects

          # Build each project
          for project in $projects; do
            cd $project
            zig build
            cd -
          done

      - name: Build Mac
        if: matrix.os == 'macos-latest'
        run: |
          # Find all folders containing build.zig, build.zig.zon, src/, src/main.zig
          projects=$(find . -type d ! -name "vkendeavors" -exec test -e "{}/build.zig" -a -e "{}/build.zig.zon" -a -e "{}/src/" -a -e "{}/src/main.zig" \; -print)
          
          echo $projects

          # Build each project
          for project in $projects; do
            cd $project
            zig build
            cd -
          done

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: |
          $projects = Get-ChildItem -Recurse -Directory | Where-Object {
            $_.Name -ne "vkendeavors" -and
            (Test-Path (Join-Path $_.FullName 'build.zig')) -and
            (Test-Path (Join-Path $_.FullName 'build.zig.zon')) -and
            (Test-Path (Join-Path $_.FullName 'src')) -and
            (Test-Path (Join-Path $_.FullName 'src/main.zig'))
          }

          Write-Host $projects

          # Build each project
          foreach ($project in $projects) {
            cd $project.FullName
            zig build
            cd $PSScriptRoot
          }
